# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2007

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags
  # Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

katex: true

pjax: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: c@cocolate.cc
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/oodavy41
  weibo: https://weibo.com/3043644997
  zhihu: 
  douban:
  pocket:
  tumblr:
  instagram:
  bilibili: 
  bangumi: https://bgm.tv/user/cocolate

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: e93n5HhEEEjOQnErokxDjoQj-gzGzoHsz
  app_key: 5aF6AzpVBq9bBVksDGgWJs1N

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-76847546-1
# Google Verification
google_verification:

# Disqus
disqus_shortname:

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

#isso
isso:
  address: pi.cocolate.cc:17850

company: 诹访大社
# ===========================================
# Version
# ===========================================
version: 0.233
